### ISSUE TITLE
Add instruction to tell users to put the file in a directory that doesn't contain spaces

### ISSUE THREAD

**Issue by Little-Karl** [Lyceris-chan/GenshinImpact#3]
[README.md](https://github.com/Lyceris-chan/GenshinImpact/files/7993159/README.md)

**Comment by Lyceris-chan** [comment]
that shouldn't be causing any issues I'm pretty sure

**Comment by Little-Karl** [comment]
yes that is
make a folder that contains spaces and put the script inside that folder and try to run it.
It's will prompt for admin privileges then nothing happens.

**Comment by Little-Karl** [comment]
yes that is an issue
make a folder that contains spaces and put the script inside that folder and try to run it.
It's will prompt for admin privileges then nothing happens.

windows 10 pro build 19041.vb_release.191206-11406

update: I found out that it only happens on drives that are other than C:

I have attached 2 videos for proof, there is 2 video 1 done on my remote computer and one on local since every time a UAC pops up obs screen goes black for 2 seconds. But doesn't happens when UAC pops up on remote machine
https://1drv.ms/f/s!AsOi60DtXXTtgagWuv39NmY5SP9SBQ
I'll add google drive later

I've made a fork on this script. The one I "modded" should fix that issue.
I've basically rewritten the entire thing. you can go check that out. sorry if I sound rude, I don't mean it, I'm just bad at English.

**Comment by Lyceris-chan** [comment]
[8af03ca](https://github.com/Lyceris-chan/GenshinImpact/commit/8af03ca2c00f2063063b4536caff578dd1f19959)
